### ISSUE TITLE
QR with large tx data is not possible

### ISSUE THREAD

**Issue by Ayanrocks** [ethessentials/wallet#6]
Generating qr with characters more than 7000 is not possible

**Comment by 0mkara** [comment]
1. create the unsigned `txHash`
2. serve an HTTP path `/getUnsignedTx/0xddde892c64c486257e4540db126fa0d154aa392794200401b8f11433ca6d1c07` where `0xddde8...` is the unsigned transaction hash
3. send the unsigned raw transaction as `response`

**Comment by Ayanrocks** [comment]
Will fix in #5
